# Generated by Django 3.2.2 on 2021-06-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='note',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
